apiVersion: v1
kind: Secret
metadata:
  name: vv-virtualmed
type: Opaque
data:
  nodeEnv: cHJvZHVjdGlvbg==
  baseUrl: aHR0cHM6Ly92aXJ0dWFsbWVkLnZpcnR1YWx2aXNpdHMuaW8K
  apiPort: MzAwMQ==
  dbHost: ci52aXJ0dWFsdmlzaXRzLmlv
  dbName: dnZfdmlydHVhbG1lZAo=
  dbPass: VjFydHZATFtWMXMxVF1z
  dbUser: dnZfdmlydHVhbG1lZF9hZG1pbgo=
# kubectl create secret generic vv-dcol \
# --from-literal=dbHost=r.virtualvisits.io \
# --from-literal=dbName=vv_dcol \
# --from-literal=baseUrl=https://dcol.virtualvisits.io \
# --from-literal=dbPass=V1rtv@L[V1s1T]s \
# --from-literal=apiPort=3001 \
# --from-literal=nodeEnv=production \
# --from-literal=dbUser=vv_dcol_admin \
# --from-literal=clientLogo=dcol-logo.png
ubectl create secret tls foo-secret --key /tmp/tls.key --cert /tmp/tls.crt
